---

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v2.3.0"
    hooks:
      - id: "check-yaml"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "pretty-format-json"
      - id: "detect-private-key"
      # Python Specific tests
      - id: "check-ast"
      - id: "fix-encoding-pragma"
      - id: "requirements-txt-fixer"

  - repo: "https://github.com/ansible-community/ansible-lint.git"
    rev: "v6.17.0"
    hooks:
      - id: "ansible-lint"
        files: \.(yaml|yml)$

...
