---

networking_defaults:
  network: 192.168.0.0
  gateway: 192.168.0.254

dns:
  cluster_id: test
  forwarder1: 8.8.8.8
  forwarder2: 1.1.1.1
  domain: openshift.local

el_packages: &EL_PACKAGES
  - "@Development Tools"
  - "@virtualization-hypervisor"
  - "@virtualization-client"
  - "@virtualization-platform"
  - "@virtualization-tools"
  - python3-lxml
  - python3-pip
  - python3-devel
  - python3-requests-oauthlib
  - cronie
  - bridge-utils
  - libguestfs-tools
  - tuned

virtualization_packages:
  fedora:
    - "@virtualization"
    - python3-lxml
    - python3-pip
    - python3-requests-oauthlib
    - cronie
    - bridge-utils
    - tuned
    - libvirt
  redhat: *EL_PACKAGES
  rocky: *EL_PACKAGES
  almalinux: *EL_PACKAGES

pip_packages:
  - openshift
  - ruamel.yaml

listen_address: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] | default('') }}"

# Are we using Hashicorp Vault
using_vault: false
...
