---

qemu_images_from_s3: false
nodes:
  image:
    bucket: "kvm-qemu-images"
  bastion:
    name: "{{ bastion_kvm_image | default('AlmaLinux-8-GenericCloud-latest.x86_64.qcow2') }}"
    url: "{{ bastion_kvm_url | default('https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/') }}"
    checksum: "{{ bastion_kvm_checksum | default('c0ad09255d91288dac590d99c95197d83a2846f1bcbec3f4222fb04265a2a4d7') }}"
    os_variant: "{{ bastion_kvm_variant | default('rhel8-unknown') }}"
    ram: "{{ bastion_kvm_ram | default(16384) }}"
    cpus: "{{ bastion_kvm_cpus | default(8) }}"
    overwrite: "{{ bastion_overwrite_kvm | default(false) }}"
  vault:
    name: "{{ vault_kvm_image | default('AlmaLinux-8-GenericCloud-latest.x86_64.qcow2') }}"
    url: "https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/"
    checksum: "c0ad09255d91288dac590d99c95197d83a2846f1bcbec3f4222fb04265a2a4d7"
    os_variant: "rhel8-unknown"
    ram: "{{ vault_kvm_ram | default(4096) }}"
    cpus: "{{ vault_kvm_cpus | default(4) }}"

s3_access_key_id: "username"
s3_secret_access_key: "password"
s3_region: "setme"
s3_url: "http://localhost:9090"
s3_validate_certs: true

admin_user: "admin"
admin_gecos: "Default admin user"
admin_groups: "users, admin, wheel"

locale: "en_GB.UTF-8"
timezone: "Europe/London"

packages:
  os:
    - libguestfs-tools
    - tar
    - zip
    - unzip
  pip:
    - boto
    - boto3
    - botocore
    - awscli

...
